accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login, name ="login"),
    path('logout/', views.logout, name = "logout"),
    path('signup/', views.signup, name = "signup"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("main/", views.index, name = "index"),
    path("post_new/", views.post_new, name="post_new"),
    path("post/<int:pk>/", views.post_detail, name = "post_detail"),
    path('post/<int:pk>/comment/new', views.comment_new, name = "comment_new"),
    path('post_edit/<int:pk>/', views.post_edit, name="post_edit"),
    path('post_delete/<int:pk>/', views.post_delete, name = "post_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('blog/', include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models

class User(AbstractUser):
    class Gender(models.TextChoices):
        Male = "M", "남성"
        Female = "F", "여성"
        X = "X", "X"

    gender = models.CharField(max_length=10, default='X', choices=Gender.choices)
    phone_number = models.CharField(max_length=13, blank=True,
                                    validators=[RegexValidator(r"010-?[1-9]\d{3}-?\d{4}$")])
    email_url = models.EmailField(max_length=29, blank=True,
                                  validators=[RegexValidator(r"^[0-9]{9}@[office.hanseo]+\.[ac.kr]+$")])
    @property
    def name(self):
        return f"{self.first_name}{self.last_name}"

blog/models.py
from django.conf import settings
from django.db import models

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(BaseModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=300, blank=True)
    caption = models.TextField(max_length=500, blank=True)
    photo = models.ImageField(blank=True)
    publish = models.BooleanField(default=True)

    class Meta:
        ordering = ['-id']

    def caption_len(self):
        return len(self.caption)

class Comment(BaseModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField(max_length=500)

    class Meta:
        ordering = ['-id']

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .models import User

class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email_url'].required = True
        self.fields['phone_number'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    def clean_phone_number(self):
        phone = self.cleaned_data.get('phone_number')
        if phone:
            qs = User.objects.filter(phone_number=phone)
            if qs.exists():
                raise forms.ValidationError("이미 등록된 핸드폰 번호입니다.")
        return phone
    def clean_email_url(self):
        email_url = self.cleaned_data.get('email_url')
        if email_url:
            qs = User.objects.filter(email_url=email_url)
            if qs.exists():
                raise forms.ValidationError("이미 등록된 이메일 주소입니다.")
        return email_url

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name', 'phone_number', 'email_url']

blog/forms.py
import os.path

from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'caption', 'photo', 'publish']
        widgets = {
            'caption' : forms.Textarea
        }

    def clean_photo(self):
        photo = self.cleaned_data.get('photo')
        if photo:
            split_name = os.path.splitext(photo.name)[-1].lower()
            if split_name not in ('.png', '.jpg'):
                raise forms.ValidationError("You must upload to Photo")
        return photo

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']
        widgets = {
            'message' : forms.Textarea(attrs={'rows' : 3})
        }

accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, logout_then_login
from django.shortcuts import render, redirect

# Create your views here.
from accounts.forms import SignUpForm

login = LoginView.as_view(template_name = "accounts/login_form.html")


@login_required
def logout(request):
    messages.success(request, "Success!!")
    return logout_then_login(request)

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '회원가입을 환영합니다.')
            return redirect("accounts:login")
    else:
        form = SignUpForm()
    return render(request, "accounts/signup_form.html",
                  {
                      "form" : form
                  })

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .models import Post, Comment
from blog.forms import PostForm, CommentForm

@login_required
def index(request):
    if Post.objects.filter(author_id=request.user):
        post_list = Post.objects.all()
    else:
        post_list = Post.objects.filter(publish=True)
    comment_form = CommentForm

    return render(request, 'blog/index.html',
                  {
                      "post_list" : post_list,
                      "comment_form" : comment_form,
                  })
@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm
    return render(request, 'blog/post_detail.html',
                  {
                      "post": post,
                      "comment_form": comment_form,
                  })

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, "포스팅 생성성공")
            return redirect("blog:index")
    else:
        form = PostForm()
    return render(request, "blog/post_form.html",
                  {
                      "form" : form
                  })

def comment_new(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method== "POST":
        form = CommentForm(request.POST, request.FILES)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            if request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest":
                return render(request, "_comment.html",
                              {
                                  "comment" : comment,
                              })
            return redirect("blog:index")
    else:
        form = CommentForm()
    return render(request, "blog/comment_form.html",
                  {
                      "form" : form,
                  })

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author:
        messages.error(request, "Error")
        return redirect("blog:index")
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.updated_at = timezone.now()
            post.save()
            return redirect(post)
    else:
        form = PostForm()
    return render(request, "blog/post_form.html",
                  {
                      "post" : post,
                  })
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user == post.author:
        post.delete()
        return redirect("blog:index")
    else:
        messages.error(request, "Error!")
    return redirect("blog:index")

templates/_comment.html
{% load static bootstrap4 %}

<div class = "card" >
    <strong>{{ comment.author }}</strong>
    <div class = "comments">
        {{ comment.message }}
    </div>
    <small class = text-muted>{{ comment.created_at }}</small>
</div>

templates/accounts/login_form.html
{% load static %}
{% load bootstrap4 %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "base_form.html" with form_title="로그인" submit_name="로그인" %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/signup_form.html
{% load static bootstrap4 %}

{% block content %}
    <div class = "container">
        <div class ="row">
            <div class = "col-sm-5">
                {% include "base_form.html" %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/ajax_comment.html
{% load bootstrap4 %}

<div class="card">
    <div class="card-header">
        <div>{{ post.author.name }}</div>
    </div>
    <div class="card-body">


        <div id="post-{{ post.pk }}-comment-list" class="comment-list mt-3 mb-3">
            {% for comment in post.comment_set.all %}
                {% include "_comment.html" %}
            {% endfor %}
        </div>

    </div>
    <div class="card-footer">
        <form id="post-{{ post.pk }}-comment-form" action="{% url "blog:comment_new" post.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <input type="submit" value="댓글 쓰기" class="btn btn-primary btn-block" />
        </form>

        <script>
        $(function() {
            var form_id = "post-{{ post.pk }}-comment-form";
            $("#" + form_id).submit(function(e) {
                e.preventDefault();

                var options = {
                    success: function(responseText, statusText, xhr, $form) {
                        console.group("ajaxSubmit response");
                        console.log(responseText);
                        console.log(statusText);
                        console.log(xhr);
                        console.log($form);
                        console.groupEnd();

                        $("#post-{{ post.pk }}-comment-list").prepend(responseText);
                    }
                };
                $(this).ajaxSubmit(options);
            });
            console.log("document ready.");
        });
        </script>
    </div>
</div>

templates/base_form.html
{% load bootstrap4 %}

<div class = "card">
    {% if form_title %}
    <div class = "card-header">
        {{ form.title }}
    </div>
    {% endif %}

    <div class ='card-body'>
        {% if form %}
            <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class = "btn btn-success">
                    {{ submit_name|default:"Submit" }}
                </button>
            {% endbuttons %}
            </form>
        {% else %}
            <div><strong>Select form Objects</strong></div>
        {% endif %}
    </div>
</div>

templates/blog/comment_form.html
{% load static %}
{% load bootstrap4 %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "base_form.html" with form_title="댓글 쓰기" submit_name="댓글쓰기" %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/blog/index.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
    <div class = "container">
        <div class = "row">
            <div class = "col-sm-5">
                <a href="{% url "blog:post_new" %} " class="btn btn-primary">새 포스팅쓰기</a>
            </div>
        </div>

        <div class = "row">
            <div class="col-sm-5">
                {% for post in post_list %}
                <div class = 'container'>
                    <hr/>
                    <div class="col-sm-5">{{ post.author }}</div>
                    <div class="text-muted"><small>{{ post.created_at }}</small></div>
                </div>
                {% if post.photo %}
                    <div><img src="{{ post.photo.url }}" width="200" height="200"> </div>
                {% else %}
                    Not Attached Photo
                {% endif %}
                    <div class="text"><strong>{{ post.caption }}</strong></div>
                    <hr/>
                                <div class="col-sm-5">
                                {% include "ajax_comment.html" %}
                                </div>
                {% if post.publish == True %}
                    <div class="text-muted"><small>Everyone can see the post</small></div>
                {% else %}
                    <div class="text-muted"><small>Only you can see the post</small></div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/post_detail.html
{% load static %}

{% block content %}
    <div class ="container">
        <div class = "row">
            <div class="col-sm-5">
                {% include "ajax_comment.html" %}
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/post_form.html
{% load static %}
{% load bootstrap4 %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "base_form.html" with form_title="새글쓰기" submit_name="새글쓰기" %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/layout.html
{% load static %}
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Instagram with Ask Company</title>

<link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" href="{% static "static/bootstrap-4.4.1-dist/css/bootstrap.min.css" %}" />
<script src="{% static "static/jquery-3.4.1.min.js" %}"></script>
<script src="{% static "static/jquery.form-3.51.0.min.js" %}"></script>
<script src="{% static "static/bootstrap-4.4.1-dist/js/bootstrap.min.js" %}"></script>

</head>
<body>

<div class="border-bottom mb-3">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white">
                    <h5 class="my-0 mr-md-auto font-weight-normal">
                        <svg class="mr-3" fill="#262626" height="24" viewBox="0 0 48 48" width="24"><path d="M13.86.13A17 17 0 008 1.26 11 11 0 003.8 4 12.22 12.22 0 001 8.28 18 18 0 00-.11 14.1c-.13 2.55-.13 3.38-.13 9.9s0 7.32.13 9.9A18 18 0 001 39.72 11.43 11.43 0 003.8 44 12.17 12.17 0 008 46.74a17.75 17.75 0 005.82 1.13c2.55.13 3.38.13 9.9.13s7.32 0 9.9-.13a17.82 17.82 0 005.83-1.13A11.4 11.4 0 0043.72 44a11.94 11.94 0 002.78-4.24 17.7 17.7 0 001.13-5.82c.13-2.55.13-3.38.13-9.9s0-7.32-.13-9.9a17 17 0 00-1.13-5.86A11.31 11.31 0 0043.72 4a12.13 12.13 0 00-4.23-2.78A17.82 17.82 0 0033.66.13C31.11 0 30.28 0 23.76 0s-7.31 0-9.9.13m.2 43.37a13.17 13.17 0 01-4.47-.83 7.25 7.25 0 01-2.74-1.79 7.25 7.25 0 01-1.79-2.74 13.23 13.23 0 01-.83-4.47c-.1-2.52-.13-3.28-.13-9.7s0-7.15.13-9.7a12.78 12.78 0 01.83-4.44 7.37 7.37 0 011.79-2.75A7.35 7.35 0 019.59 5.3a13.17 13.17 0 014.47-.83c2.52-.1 3.28-.13 9.7-.13s7.15 0 9.7.13a12.78 12.78 0 014.44.83 7.82 7.82 0 014.53 4.53 13.12 13.12 0 01.83 4.44c.13 2.51.13 3.27.13 9.7s0 7.15-.13 9.7a13.23 13.23 0 01-.83 4.47 7.9 7.9 0 01-4.53 4.53 13 13 0 01-4.44.83c-2.51.1-3.28.13-9.7.13s-7.15 0-9.7-.13m19.63-32.34a2.88 2.88 0 102.88-2.88 2.89 2.89 0 00-2.88 2.88M11.45 24a12.32 12.32 0 1012.31-12.35A12.33 12.33 0 0011.45 24m4.33 0a8 8 0 118 8 8 8 0 01-8-8"></path></svg>
                    </h5>
                </div>
            </div>
        </div>
    </div>
</div>

{% block content %}
{% endblock %}

<div class="border-top mt-3">

<div class="container">
<footer class="pt-4 my-md-5 pt-md-5">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">© 2017-2019</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Cool stuff</a></li>
          <li><a class="text-muted" href="#">Random feature</a></li>
          <li><a class="text-muted" href="#">Team feature</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>
          <li><a class="text-muted" href="#">Another one</a></li>
          <li><a class="text-muted" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Resource</a></li>
          <li><a class="text-muted" href="#">Resource name</a></li>
          <li><a class="text-muted" href="#">Another resource</a></li>
          <li><a class="text-muted" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Locations</a></li>
          <li><a class="text-muted" href="#">Privacy</a></li>
          <li><a class="text-muted" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>
</div>

</body>
</html>